# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - develop
  - releases/*

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    condition: not(startsWith(variables['Build.SourceBranch'], 'releases'))
    displayName: "Running package"
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m '
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      goals: 'verify'
  
  - task: Maven@3
    condition: startsWith(variables['Build.SourceBranch'], 'releases')
    displayName: "Release"
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      goals: 'deploy'