# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: DockerCompose@0
    displayName: "Run a database"
    inputs:
      dockerComposeFile: "docker-compose.yml"
      dockerComposeCommand: "up --abort-on-container-exit"
      detached: true
      qualifyImageNames: true
      serviceName: mysql
  - task: Maven@3
    displayName: "Running package"
    env:
      IGNORE-IT: "true"
      IGNORE-TEST: "false"
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      goals: 'package'