# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - develop
  - releases/*

pool:
  vmImage: ubuntu-latest

steps:

  - task: MavenAuthenticate@0
    displayName: 'Maven Authenticate'
    inputs:
      artifactsFeeds: iaivaldi
  - task: Maven@3
    condition: not(contains(variables['Build.SourceBranch'], 'releases'))
    displayName: "Running package"
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      goals: 'verify'
  
  - task: Maven@3
    condition: contains(variables['Build.SourceBranch'], 'releases')
    displayName: "Release"
    env:
      BUILD_VALUE: $(Build.BuildNumber)
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      goals: 'deploy'