version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: testdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./src/tests/resources/docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysql -pabc123 -D testdb -e "SELECT * FROM test1;"
      interval: 3s
      timeout: 60s
      retries: 10